import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>pong game</title>
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  )
}
