version: "3"

services:
  database:
    image: postgres:latest
    container_name: mydb
    ports:
      - 5432:5432
    restart: on-failure
    env_file:
      - .env
    networks:
      - trans
  frontend:
    build: ./frontend
    restart: on-failure
    container_name: frontend
    ports:
      - 8000:8000
    env_file:
      - ./frontend/.env
    networks:
      - trans
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: on-failure
    container_name: backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    networks:
      - trans
    depends_on:
      - database

networks:
  trans:
