version: "3"

services:
  database:
    image: postgres:latest
    container_name: mydb
    ports:
      - 5432:5432
    restart: on-failure
    env_file:
      - .env
    networks:
      - trans
    volumes:
      - db:/var/lib/postgresql/data
  # frontend:
  #   image: node:latest
  #   restart: on-failure
  #   container_name: myfrontend
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - .env
  #   networks:
  #     - trans
  # backend:
  #   image: node:latest
  #   restart: on-failure
  #   container_name: mybackend
  #   command: npm start dev && npx prisma migrate dev --name init
  #   ports:
  #     - 9090:9090
  #   env_file:
  #     - .env
  #   networks:
  #     - trans

networks:
  trans:
# services:
#   db:
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     env_file:
#       - .env
#     networks:
#       - trans

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /Users/mjlem/Desktop/db
