version: '3'

services:
  database:
    image: postgres:latest
    container_name: mydb
    ports:
      - 5432:5432
    restart: on-failure
    env_file:
      - .env
    networks:
      - trans
  frontend:
    image: node:20
    restart: on-failure
    container_name: myfrontend
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - trans
  backend:
    image: node:20
    restart: on-failure
    container_name: mybackend
    command: npm start dev && npx prisma migrate dev --name init
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - trans

networks:
  trans:
# services:
#   db:
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     env_file:
#       - .env 
#     networks:
#       - trans

